# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/two_bit_adder.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_half_adder_0_0/design_1_half_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_half_adder_0_0 || ORIG_REF_NAME==design_1_half_adder_0_0}]

# IP: bd/design_1/ip/design_1_half_adder_1_0/design_1_half_adder_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_half_adder_1_0 || ORIG_REF_NAME==design_1_half_adder_1_0}]

# IP: bd/design_1/ip/design_1_half_adder_2_0/design_1_half_adder_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_half_adder_2_0 || ORIG_REF_NAME==design_1_half_adder_2_0}]

# IP: bd/design_1/ip/design_1_half_adder_3_0/design_1_half_adder_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_half_adder_3_0 || ORIG_REF_NAME==design_1_half_adder_3_0}]

# XDC: bd/design_1/design_1_ooc.xdc
